version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - java --version
      - pip3 install --upgrade pip
      - pip3 install --upgrade awscli
      - docker info
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls
      - cd OpenATM/Microservice/ExtractTransformFunction
      - gradle build
      - cd ..
      - sam build
      #- docker build -t open_atm:$CODEBUILD_BUILD_NUMBER .
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr get-login-password --region ap-southeast-1
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 238815075413.dkr.ecr.ap-southeast-1.amazonaws.com
      #- docker tag open_atm:$CODEBUILD_BUILD_NUMBER 238815075413.dkr.ecr.ap-southeast-1.amazonaws.com/open_atm:$CODEBUILD_BUILD_NUMBER
      #- docker push 238815075413.dkr.ecr.ap-southeast-1.amazonaws.com/open_atm:$CODEBUILD_BUILD_NUMBER
      - docker tag extracttransformfunction 238815075413.dkr.ecr.ap-southeast-1.amazonaws.com/open_atm:$CODEBUILD_BUILD_NUMBER
      - docker push 238815075413.dkr.ecr.ap-southeast-1.amazonaws.com/open_atm:$CODEBUILD_BUILD_NUMBER
  artifacts:
    files:
      - '**/*'
    base-directory: base_dir
    name: BuildArtifact
    discard-paths: no
