version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket codepipeline-ap-southeast-1-558343094238 --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yml
