version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "OpenATM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1890yrqc8jzmm"
s3_prefix = "OpenATM"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
